spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

    web:
      pageable:
        default-page-size: 30

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect: http://localhost:8080/oauth/redirected/kakao

springdoc:
  swagger-ui:
    url: ${SWAGGER_UI_URL}
    path: ${SWAGGER_UI_PATH}

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
