name: ComeOn App Dev CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # JDK 설정
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

          # 환경 변수 설정
      - name: Set up Environment
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./.env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and Build
        run: |
          ./gradlew clean test -Pprofile=test
          ./gradlew clean build

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/boot-prac-ci .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/boot-prac-ci:latest

        # 환경 변수 파일 서버로 전달하기(복사 후 붙여넣기)
      - name: Send env file
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./.env"
          target: "/home/ec2-user"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker ps -q | grep -v $(sudo docker ps -qf "name=back_mysql") | grep -v $(sudo docker ps -qf "name=redis") | xargs -r sudo docker stop
            sudo docker ps -aq | grep -v $(sudo docker ps -aqf "name=back_mysql") | grep -v $(sudo docker ps -aqf "name=redis") | xargs -r sudo docker rm
            sudo docker image prune -a -f
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/boot-prac-ci:latest
            sudo docker run -d --log-driver=syslog --env-file .env -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/boot-prac-ci:latest
